Feature/fwk
TechTeamer/kiosk-poc pull request #5
Opened 2022-08-02 12:44 UTC by kzsolt1984

2022-08-02 13:01 UTC, chrismakaay requested changes

2022-08-02 13:01 UTC, chrismakaay commented on client/ui/layouts/default/default.layout.js
>  for( let i = 0; i < pageSelectors.length; i++) {
pageSelectors.forEach((pageSelector) => {

2022-08-02 13:01 UTC, chrismakaay commented on client/ui/layouts/default/default.layout.js
>          window.electronAPI.changePage(pageSelectors[i].dataset.page)
Nem kéne megvizsgálni, hogy van e értéke a dataset.page-nek?

2022-08-02 14:38 UTC, kzsolt1984 commented on client/ui/layouts/default/default.layout.js
>          window.electronAPI.changePage(pageSelectors[i].dataset.page)
hibakezelés v0.7 része, húzzad

2022-08-04 07:57 UTC, gab3sz approved these changes

2022-08-04 07:58 UTC, merged